# Generated by Django 6.0 on 2025-12-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.TextField()),
                ("skill_requirements", models.JSONField()),
                ("company_size", models.CharField(max_length=50)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("num_employees", models.IntegerField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills_vector", models.JSONField()),
                ("availability_places", models.IntegerField()),
                ("historical_success_rate", models.FloatField()),
                ("vector_length", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.sector"
            ),
        ),
    ]
