# Generated by Django 6.0 on 2025-12-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other/I prefer not to say"),
                        ],
                        max_length=10,
                    ),
                ),
                ("course_year", models.IntegerField(blank=True, null=True)),
                ("academy_training", models.TextField()),
                ("speciality", models.CharField(max_length=100)),
                ("skills", models.JSONField()),
                ("num_skills", models.IntegerField(blank=True, null=True)),
                ("availability", models.BooleanField(default=True)),
                (
                    "availability_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("mornings", "Mornings"),
                            ("afternoons", "Afternoons"),
                            ("evenings", "Evenings"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills_vector", models.JSONField()),
                ("success_probability", models.FloatField(blank=True, null=True)),
                ("availability", models.BooleanField(default=True)),
                (
                    "availability_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("vector_length", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
