# Generated by Django 6.0 on 2025-12-04 23:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_hours_planned", models.IntegerField()),
                ("actual_hours_completed", models.IntegerField(blank=True, null=True)),
                ("company_mentor", models.CharField(max_length=100)),
                (
                    "internship_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("final_tutor_valuation", models.FloatField(blank=True, null=True)),
                ("duration_weeks", models.FloatField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="companies.company",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "hours_performed",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("cumulative_hours", models.IntegerField(blank=True, null=True)),
                ("day_of_week", models.IntegerField(blank=True, null=True)),
                ("is_weekend", models.BooleanField(blank=True, null=True)),
                ("activities", models.TextField()),
                (
                    "tutor_valuation",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("emotional_state", models.TextField(blank=True, null=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="internships.internship",
                    ),
                ),
            ],
        ),
    ]
