# Generated by Django 6.0 on 2025-12-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMatches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.BooleanField()),
                (
                    "actual_duration_of_internships",
                    models.IntegerField(
                        help_text="Duración real de la práctica en horas o semanas"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("student_age", models.IntegerField(blank=True, null=True)),
                (
                    "company_sector",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("match_type", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_matches",
                        to="companies.company",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_matches",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("student_age", models.IntegerField(blank=True, null=True)),
                ("student_year", models.IntegerField(blank=True, null=True)),
                ("num_skills", models.IntegerField(blank=True, null=True)),
                (
                    "company_sector",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("applied", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicted_matches",
                        to="companies.company",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicted_matches",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "company")},
            },
        ),
        migrations.CreateModel(
            name="MatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("features_used", models.JSONField()),
                ("score", models.FloatField()),
                (
                    "matching_algorithm_version",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "predicted_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="matches.predictedmatch",
                    ),
                ),
            ],
        ),
    ]
